version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jirarush
    container_name: jira
    environment:
      - LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITLAB_CLIENT_ID=${GITLAB_CLIENT_ID}
      - GITLAB_CLIENT_SECRET=${GITLAB_CLIENT_SECRET}
      - GITLAB_CLIENT_NAME=${GITLAB_CLIENT_NAME}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - new-network

  db:
    image: postgres:17
    container_name: jira-db
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jira -d jira -p 5432"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - new-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - new-network

networks:
  new-network:
    driver: bridge


volumes:
  postgres-data:
    driver: local